# TELEGRAM
telegram:
  bot_username: ${BOT_USERNAME}
  bot_token: ${BOT_TOKEN}
  bot_path: ${BOT_PATH}
  compatible_formats:
    - epub
    - mobi

# SPRING
spring:
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# OTHER
locale:
  tag: ru-RU
